<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ChannelsSeeder extends Seeder
{
    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        DB::table('logistics_channels')->truncate();

        DB::table('logistics_channels')->insert([
            [
                'id' => 1,
                'provider_id' => 1,
                'code' => 'EUB-SZ',
                'title' => '省内EUB',
                'en' => 'Guangdong EUB',
                'status' => 1,
                'sort' => 0,
            ],
            [
                'id' => 2,
                'provider_id' => 1,
                'code' => 'CNDWA',
                'title' => '华南快速小包平邮(DG)',
                'en' => 'China Post Unregistered Air Mail-DongGuan',
                'status' => 1,
                'sort' => 0,
            ],
            [
                'id' => 3,
                'provider_id' => 1,
                'code' => 'HKRDGM',
                'title' => 'HK DHL eCommerce挂号',
                'en' => 'HK DHL eCommerce Registration Mail',
                'status' => 0,
                'sort' => 0,
            ],
            [
                'id' => 4,
                'provider_id' => 1,
                'code' => 'HKADGM',
                'title' => 'HK DHL eCommerce平邮',
                'en' => 'HK DHL eCommerce Unregistered Mail',
                'status' => 0,
                'sort' => 0,
            ],
            [
                'id' => 5,
                'provider_id' => 1,
                'code' => 'NLPOST',
                'title' => '特惠28国',
                'en' => 'Promotional 28 countries',
                'status' => 0,
                'sort' => 0,
            ],
            [
                'id' => 6,
                'provider_id' => 1,
                'code' => 'CNDWR',
                'title' => '华南快速小包挂号(DG)',
                'en' => 'China Post Registered Air Mail-DongGuan',
                'status' => 0,
                'sort' => 0,
            ],
            [
                'id' => 7,
                'provider_id' => 1,
                'code' => 'EUB-FZ',
                'title' => '福州EUB',
                'en' => 'FuZhou EUB',
                'status' => 0,
                'sort' => 0,
            ],
            [
                'id' => 8,
                'provider_id' => 1,
                'code' => 'SGRDGM',
                'title' => 'DHL eCommerce 12国挂号',
                'en' => 'Singapore DHL eCommerce Registration Mail',
                'status' => 0,
                'sort' => 0,
            ],
            [
                'id' => 9,
                'provider_id' => 1,
                'code' => 'ST',
                'title' => '测试申通(勿下单)',
                'en' => 'st',
                'status' => 0,
                'sort' => 0,
            ],
            [
                'id' => 10,
                'provider_id' => 1,
                'code' => 'CNDWA-D',
                'title' => '华南平邮特惠',
                'en' => 'China Post Unregistered Air Mail-DongGuan-TH',
                'status' => 0,
                'sort' => 0,
            ],
            [
                'id' => 11,
                'provider_id' => 1,
                'code' => 'SMT-XSA',
                'title' => '速卖通线上平邮(DG)',
                'en' => 'AliExpress Online Unregistered Air Mail-DG',
                'status' => 0,
                'sort' => 0,
            ],
            [
                'id' => 12,
                'provider_id' => 1,
                'code' => 'SMT-XSR',
                'title' => '速卖通线上挂号(DG)',
                'en' => 'AliExpress Online Registered Air Mail-DG',
                'status' => 0,
                'sort' => 0,
            ],
            [
                'id' => 13,
                'provider_id' => 1,
                'code' => 'EMS-FZ',
                'title' => '福州EMS',
                'en' => 'China Post EMS-FuZhou',
                'status' => 0,
                'sort' => 0,
            ],
            [
                'id' => 14,
                'provider_id' => 1,
                'code' => 'HKDHL',
                'title' => 'DHL快递(香港)',
                'en' => 'HongKong DHL Express',
                'status' => 1,
                'sort' => 0,
            ],
            [
                'id' => 15,
                'provider_id' => 1,
                'code' => 'ETK',
                'title' => 'E特快',
                'en' => 'China Post  Ems-FuZhou',
                'status' => 0,
                'sort' => 0,
            ],
            [
                'id' => 16,
                'provider_id' => 1,
                'code' => 'DHLCN-B',
                'title' => '大陆DHL大货价',
                'en' => 'China DHL Express-B',
                'status' => 0,
                'sort' => 0,
            ],
            [
                'id' => 17,
                'provider_id' => 1,
                'code' => 'SGADGM',
                'title' => 'DHL eCommerce 12国平邮',
                'en' => 'Singapore DHL eCommerce Unregistered Mail',
                'status' => 0,
                'sort' => 0,
            ],
            [
                'id' => 18,
                'provider_id' => 1,
                'code' => 'BPA',
                'title' => '云途-B 小包平邮+',
                'en' => 'HK bpost',
                'status' => 0,
                'sort' => 0,
            ],
            [
                'id' => 19,
                'provider_id' => 1,
                'code' => 'TWYZA',
                'title' => '云途快速小包平邮',
                'en' => 'Yunexpress Unregistered Air Mail',
                'status' => 0,
                'sort' => 0,
            ],
            [
                'id' => 20,
                'provider_id' => 1,
                'code' => 'CNDWR-D',
                'title' => '华南挂号特惠',
                'en' => 'China Post Registered Air Mail-DONG',
                'status' => 0,
                'sort' => 0,
            ],
            [
                'id' => 21,
                'provider_id' => 1,
                'code' => 'GBRYMA',
                'title' => '英国专线平邮',
                'en' => 'YunExpress Britain Direct Untracked Line',
                'status' => 0,
                'sort' => 0,
            ],
            [
                'id' => 22,
                'provider_id' => 1,
                'code' => 'FBAUSB',
                'title' => 'FBA美国专线标准线(可带电)',
                'en' => 'US-FBA Direct Priority Line(battery accepted)',
                'status' => 0,
                'sort' => 0,
            ],
            [
                'id' => 23,
                'provider_id' => 1,
                'code' => 'DEZXR',
                'title' => '德国专线挂号',
                'en' => 'YunExpress Germany Direct Line',
                'status' => 0,
                'sort' => 0,
            ],
            [
                'id' => 24,
                'provider_id' => 1,
                'code' => 'GBZXR',
                'title' => '英国专线标准',
                'en' => 'YunExpress Britain Direct Line',
                'status' => 0,
                'sort' => 0,
            ],
            [
                'id' => 25,
                'provider_id' => 1,
                'code' => 'PK0009',
                'title' => '测试总包',
                'en' => 'CSXB',
                'status' => 0,
                'sort' => 0,
            ],
            [
                'id' => 26,
                'provider_id' => 1,
                'code' => 'FBAUSDL',
                'title' => 'FBA美国专线标准线(同行)',
                'en' => 'US-FBA Direct Priority Line(battery accepted)-T',
                'status' => 0,
                'sort' => 0,
            ],
            [
                'id' => 27,
                'provider_id' => 1,
                'code' => 'JPFBA',
                'title' => '日本FBA专线(普货)',
                'en' => 'JP-FBA Direct Line(battery not accepted)',
                'status' => 0,
                'sort' => 0,
            ],
            [
                'id' => 28,
                'provider_id' => 1,
                'code' => 'CS--',
                'title' => '测试---',
                'en' => 'CS--',
                'status' => 0,
                'sort' => 0,
            ],
            [
                'id' => 29,
                'provider_id' => 1,
                'code' => 'EUFBAE',
                'title' => '中欧FBA专线',
                'en' => 'EU-FBA Direct Line',
                'status' => 0,
                'sort' => 0,
            ],
            [
                'id' => 30,
                'provider_id' => 1,
                'code' => 'ESZXA',
                'title' => '西班牙专线平邮',
                'en' => 'YunExpress Spain Direct Untracked Line',
                'status' => 0,
                'sort' => 0,
            ],
            [
                'id' => 31,
                'provider_id' => 1,
                'code' => 'USZMTK',
                'title' => '中美专线(标快)',
                'en' => 'YunExpress US Direct Priority Line',
                'status' => 0,
                'sort' => 0,
            ],
            [
                'id' => 32,
                'provider_id' => 1,
                'code' => 'FRZXR',
                'title' => '法国专线挂号',
                'en' => 'YunExpress France Direct Line',
                'status' => 0,
                'sort' => 0,
            ],
            [
                'id' => 33,
                'provider_id' => 1,
                'code' => 'FBAUSBZP',
                'title' => 'FBA美国专线标准线(普货)',
                'en' => 'US-FBA Direct Priority Line(battery not accepted)',
                'status' => 0,
                'sort' => 0,
            ],
            [
                'id' => 34,
                'provider_id' => 1,
                'code' => 'PK0014',
                'title' => '日本专线挂号',
                'en' => 'YunExpress Japan Direct Line',
                'status' => 0,
                'sort' => 0,
            ],
            [
                'id' => 35,
                'provider_id' => 1,
                'code' => 'ESZXG',
                'title' => '西班牙专线挂号',
                'en' => 'YunExpress Spain Direct Line',
                'status' => 0,
                'sort' => 0,
            ],
            [
                'id' => 36,
                'provider_id' => 1,
                'code' => 'PK00012',
                'title' => '测试,忽略',
                'en' => '测试,忽略',
                'status' => 0,
                'sort' => 0,
            ],
            [
                'id' => 37,
                'provider_id' => 1,
                'code' => 'CP0004',
                'title' => '测试四产',
                'en' => 'ceshisichan',
                'status' => 0,
                'sort' => 0,
            ],
            [
                'id' => 38,
                'provider_id' => 1,
                'code' => 'MXZXR',
                'title' => '墨西哥快邮小包',
                'en' => 'Mexico Direct Line',
                'status' => 0,
                'sort' => 0,
            ],
            [
                'id' => 39,
                'provider_id' => 1,
                'code' => 'PK0018',
                'title' => '测试荷兰小包',
                'en' => 'ceshi',
                'status' => 0,
                'sort' => 0,
            ],
            [
                'id' => 40,
                'provider_id' => 1,
                'code' => 'WS-XSA-DG',
                'title' => 'Wish邮平邮(DG)',
                'en' => 'Wishpost Unregistered Air Mail-DG',
                'status' => 0,
                'sort' => 0,
            ],
            [
                'id' => 41,
                'provider_id' => 1,
                'code' => 'WS-XSR-DG',
                'title' => 'Wish邮挂号(DG)',
                'en' => 'Wishpost Registered Air Mial-DG',
                'status' => 0,
                'sort' => 0,
            ],
            [
                'id' => 42,
                'provider_id' => 1,
                'code' => 'ZDZXR',
                'title' => '中东专线',
                'en' => 'Middle East Direct Line',
                'status' => 0,
                'sort' => 0,
            ],
            [
                'id' => 43,
                'provider_id' => 1,
                'code' => 'FRZXRS',
                'title' => '法国专线挂号(签名)',
                'en' => 'YunExpress France Direct Line(signature)',
                'status' => 0,
                'sort' => 0,
            ],
            [
                'id' => 44,
                'provider_id' => 1,
                'code' => 'CAFBATK',
                'title' => '加拿大FBA专线(可带电)',
                'en' => 'CA-FBA Direct Priority Line(battery accepted)',
                'status' => 0,
                'sort' => 0,
            ],
            [
                'id' => 45,
                'provider_id' => 1,
                'code' => 'CAFBA',
                'title' => '加拿大FBA专线(普货)',
                'en' => 'CA-FBA Direct Priority Line(battery not accepted)',
                'status' => 0,
                'sort' => 0,
            ],
            [
                'id' => 46,
                'provider_id' => 1,
                'code' => 'FBAUSSEA',
                'title' => 'FBA美国专线(海运)',
                'en' => 'US-FBA Direct Priority Line(Shipping by sea)',
                'status' => 0,
                'sort' => 0,
            ],
            [
                'id' => 47,
                'provider_id' => 1,
                'code' => 'WSR-DG-F',
                'title' => 'Wish邮挂号',
                'en' => 'Wishpost Registered Air Mial-DG-F',
                'status' => 0,
                'sort' => 0,
            ],
            [
                'id' => 48,
                'provider_id' => 1,
                'code' => 'WSA-DG-F',
                'title' => 'Wish邮平邮',
                'en' => 'Wishpost Unregistered Air Mail-DG-F',
                'status' => 0,
                'sort' => 0,
            ],
            [
                'id' => 49,
                'provider_id' => 1,
                'code' => 'SMT-XSR-F',
                'title' => '速卖通线上挂号',
                'en' => 'AliExpress Online Registered Air Mail-DG-F',
                'status' => 0,
                'sort' => 0,
            ],
            [
                'id' => 50,
                'provider_id' => 1,
                'code' => 'SMT-XSA-F',
                'title' => '速卖通线上平邮',
                'en' => 'AliExpress Online Unregistered Air Mail-DG-F',
                'status' => 0,
                'sort' => 0,
            ],
            [
                'id' => 51,
                'provider_id' => 1,
                'code' => 'WISHDER',
                'title' => 'wish邮云途德法专线挂号',
                'en' => 'Wish YunExpress Germany Drict Line',
                'status' => 0,
                'sort' => 0,
            ],
            [
                'id' => 52,
                'provider_id' => 1,
                'code' => 'KLD',
                'title' => 'ST(单独询价)',
                'en' => 'sut',
                'status' => 0,
                'sort' => 0,
            ],
            [
                'id' => 53,
                'provider_id' => 1,
                'code' => 'ETK-SC',
                'title' => '四川E特快',
                'en' => 'Sichuan ETK',
                'status' => 0,
                'sort' => 0,
            ],
            [
                'id' => 54,
                'provider_id' => 1,
                'code' => 'JMZXP',
                'title' => 'Joom邮云途专线平邮',
                'en' => 'Joom YunExpress untrack Direct Line',
                'status' => 0,
                'sort' => 0,
            ],
            [
                'id' => 55,
                'provider_id' => 1,
                'code' => 'JMZXR',
                'title' => 'Joom邮云途专线挂号',
                'en' => 'Joom YunExpress Direct Line',
                'status' => 0,
                'sort' => 0,
            ],
            [
                'id' => 56,
                'provider_id' => 1,
                'code' => 'INFBA',
                'title' => '印度FBA专线标准线',
                'en' => 'IN-FBA Direct Line',
                'status' => 0,
                'sort' => 0,
            ],
            [
                'id' => 57,
                'provider_id' => 1,
                'code' => 'INZXR-TEST',
                'title' => '印度专线挂号测试',
                'en' => 'India Direct line-tracked-test',
                'status' => 0,
                'sort' => 0,
            ],
            [
                'id' => 58,
                'provider_id' => 1,
                'code' => 'FRZXP',
                'title' => '法国专线平邮',
                'en' => 'YunExpress French Direct Untracked Line',
                'status' => 0,
                'sort' => 0,
            ],
            [
                'id' => 59,
                'provider_id' => 1,
                'code' => 'JPFBA-B',
                'title' => '日本FBA专线(可带电)',
                'en' => 'JP-FBA Direct Line(battery accepted)',
                'status' => 0,
                'sort' => 0,
            ],
            [
                'id' => 60,
                'provider_id' => 1,
                'code' => 'JPFBA-SEA',
                'title' => '日本FBA专线(海运)',
                'en' => 'JP-FBA Direct Priority Line(Shipping by sea)',
                'status' => 0,
                'sort' => 0,
            ],
            [
                'id' => 61,
                'provider_id' => 1,
                'code' => 'INFBATH',
                'title' => '印度FBA专线特惠线',
                'en' => 'IN-FBA Direct Economy Line',
                'status' => 0,
                'sort' => 0,
            ],
            [
                'id' => 62,
                'provider_id' => 1,
                'code' => 'JOOM-XSA',
                'title' => 'JOOM(DG)-平邮',
                'en' => 'JOOM Unregistered Air Mail-DG',
                'status' => 0,
                'sort' => 0,
            ],
            [
                'id' => 63,
                'provider_id' => 1,
                'code' => 'JOOM-XSR',
                'title' => 'JOOM(DG)-挂号',
                'en' => 'JOOM Registered Air Mial-DG',
                'status' => 0,
                'sort' => 0,
            ],
            [
                'id' => 64,
                'provider_id' => 1,
                'code' => 'BKZXR',
                'title' => '云途全球专线挂号（标快）',
                'en' => 'YunExpress Global Direct Line',
                'status' => 1,
                'sort' => 0,
            ],
            [
                'id' => 65,
                'provider_id' => 1,
                'code' => 'BKZXU',
                'title' => '云途全球专线平邮（标快）',
                'en' => 'YunExpress Global Direct Untracked Line',
                'status' => 0,
                'sort' => 0,
            ],
            [
                'id' => 66,
                'provider_id' => 1,
                'code' => 'THPHR',
                'title' => '云途全球专线挂号（特惠普货）',
                'en' => 'Yunexpress Global Driect Economical Line（general）',
                'status' => 1,
                'sort' => 0,
            ],
            [
                'id' => 67,
                'provider_id' => 1,
                'code' => 'CNDWR-B',
                'title' => '华南快速小包挂号(DG)-带电',
                'en' => 'China Post Registered Air Mail-DongGuan-B',
                'status' => 0,
                'sort' => 0,
            ],
            [
                'id' => 68,
                'provider_id' => 1,
                'code' => 'CNDWA-B',
                'title' => '华南快速小包平邮(DG)-带电',
                'en' => 'China Post Unregistered Air Mail-DongGuan-B',
                'status' => 0,
                'sort' => 0,
            ],
            [
                'id' => 69,
                'provider_id' => 1,
                'code' => 'WS-XSA-DGB',
                'title' => 'wish邮平邮(DG)-带电',
                'en' => 'post Unregistered Air Mail-DG-B',
                'status' => 0,
                'sort' => 0,
            ],
            [
                'id' => 70,
                'provider_id' => 1,
                'code' => 'WS-XSR-DGB',
                'title' => 'wish邮挂号(DG)-带电',
                'en' => 'ishpost Registered Air Mial-DGB',
                'status' => 0,
                'sort' => 0,
            ],
            [
                'id' => 71,
                'provider_id' => 1,
                'code' => 'WSA-DG-FB',
                'title' => 'Wish邮平邮(DG)-F-带电',
                'en' => 'Wishpost Unregistered Air Mail-DG-FB',
                'status' => 0,
                'sort' => 0,
            ],
            [
                'id' => 72,
                'provider_id' => 1,
                'code' => 'WSR-DG-FB',
                'title' => 'Wish邮挂号(DG)-F-带电',
                'en' => 'Wishpost Registered Air Mial-DG-FB',
                'status' => 0,
                'sort' => 0,
            ],
            [
                'id' => 73,
                'provider_id' => 1,
                'code' => 'DEZXRT',
                'title' => '德国专线挂号(退货)',
                'en' => 'YunExpress Germany Return Line',
                'status' => 0,
                'sort' => 0,
            ],
            [
                'id' => 74,
                'provider_id' => 1,
                'code' => 'HXEUB',
                'title' => '华西EUB',
                'en' => 'EUB-HuaXi',
                'status' => 0,
                'sort' => 0,
            ],
            [
                'id' => 75,
                'provider_id' => 1,
                'code' => 'THZXR',
                'title' => '云途全球专线挂号（特惠带电）',
                'en' => 'Yunexpress Global Driect Economical Line',
                'status' => 1,
                'sort' => 0,
            ],
            [
                'id' => 76,
                'provider_id' => 1,
                'code' => 'THZXU',
                'title' => '云途全球专线平邮（特惠带电）',
                'en' => 'Yunexpress Global Driect Economical Untracked Line',
                'status' => 0,
                'sort' => 0,
            ],
            [
                'id' => 77,
                'provider_id' => 1,
                'code' => 'THPHU',
                'title' => '云途全球专线平邮（特惠普货）',
                'en' => 'Yunexpress Driect Economical Untrack Line(general)',
                'status' => 0,
                'sort' => 0,
            ],
            [
                'id' => 78,
                'provider_id' => 1,
                'code' => 'FBACD-GB',
                'title' => '中欧FBA专线CD直飞(英国VAT-普货)',
                'en' => 'A Direct Line(GB VAT-ordinary)',
                'status' => 0,
                'sort' => 0,
            ],
            [
                'id' => 79,
                'provider_id' => 1,
                'code' => 'SNETK',
                'title' => '省内E特快',
                'en' => 'China Post  Ems-SN',
                'status' => 0,
                'sort' => 0,
            ],
            [
                'id' => 80,
                'provider_id' => 1,
                'code' => 'SZEMS',
                'title' => '省内EMS',
                'en' => 'China Post EMS-SN',
                'status' => 0,
                'sort' => 0,
            ],
            [
                'id' => 81,
                'provider_id' => 1,
                'code' => 'DEZXRT2',
                'title' => '德国专线简易挂号',
                'en' => 'YunExpress Germany  Simple Registration',
                'status' => 0,
                'sort' => 0,
            ],
            [
                'id' => 82,
                'provider_id' => 1,
                'code' => 'PK0046',
                'title' => '渠道一部测试',
                'en' => 'test test',
                'status' => 0,
                'sort' => 0,
            ],
            [
                'id' => 83,
                'provider_id' => 1,
                'code' => 'SYEUB',
                'title' => '华东EUB',
                'en' => 'EUB-HD',
                'status' => 0,
                'sort' => 0,
            ],
            [
                'id' => 84,
                'provider_id' => 1,
                'code' => 'TPHZXR',
                'title' => 'Tophatter云途专线挂号',
                'en' => 'Tophatter Yunexpress  Direct Line',
                'status' => 0,
                'sort' => 0,
            ],
            [
                'id' => 85,
                'provider_id' => 1,
                'code' => 'HNTH-EUB',
                'title' => '华南特惠EUB',
                'en' => 'HNTH-EUB',
                'status' => 0,
                'sort' => 0,
            ],
            [
                'id' => 86,
                'provider_id' => 1,
                'code' => 'ZDZXDDP',
                'title' => '中东专线-DDP',
                'en' => 'Middle East Direct Line DDP',
                'status' => 0,
                'sort' => 0,
            ],
            86 =>
            [
                'id' => 87,
                'provider_id' => 1,
                'code' => 'FBADENT',
                'title' => '中欧FBA专线（德国VAT-可带电）',
                'en' => 'EU-FBA Direct Line(Germany VAT-battery)',
                'status' => 0,
                'sort' => 0,
            ],
            [
                'id' => 88,
                'provider_id' => 1,
                'code' => 'FBADENTP',
                'title' => '中欧FBA专线（德国VAT-普货）',
                'en' => 'EU-FBA Direct Line(Germany VAT-ordinary)',
                'status' => 0,
                'sort' => 0,
            ],
            [
                'id' => 89,
                'provider_id' => 1,
                'code' => 'FBAEGBTNB',
                'title' => '中欧FBA专线（英国VAT-普货）',
                'en' => 'EU-FBA Direct Line(GB VAT-ordinary)',
                'status' => 0,
                'sort' => 0,
            ],
            [
                'id' => 90,
                'provider_id' => 1,
                'code' => 'FBAGBNT',
                'title' => '中欧FBA专线（英国VAT-可带电）',
                'en' => 'EU-FBA Direct Line(GB VAT-battery)',
                'status' => 0,
                'sort' => 0,
            ],
            [
                'id' => 91,
                'provider_id' => 1,
                'code' => 'GBZXA',
                'title' => '测试提交+总包',
                'en' => 'Small Packet of Special Line for England',
                'status' => 1,
                'sort' => 0,
            ],
            [
                'id' => 92,
                'provider_id' => 1,
                'code' => 'USZXRS',
                'title' => '中美专线(测试)',
                'en' => 'US Direct Line(test-CA)',
                'status' => 1,
                'sort' => 0,
            ],
            [
                'id' => 93,
                'provider_id' => 1,
                'code' => 'ESCP',
                'title' => '重派--西班牙邮政',
                'en' => 'Reship-Correos',
                'status' => 1,
                'sort' => 0,
            ],
            [
                'id' => 94,
                'provider_id' => 1,
                'code' => 'CPA',
                'title' => '测试渠道二',
                'en' => 'ceshiyichan',
                'status' => 1,
                'sort' => 0,
            ],
            [
                'id' => 95,
                'provider_id' => 1,
                'code' => 'UPSSC',
                'title' => '四川UPS',
                'en' => 'UPS Worldwide Expredited-SICHUAN',
                'status' => 1,
                'sort' => 0,
            ],
            [
                'id' => 96,
                'provider_id' => 1,
                'code' => 'UPSSC-A',
                'title' => '四川UPS大货',
                'en' => 'UPS Worldwide Expredited-SICHUAN-A',
                'status' => 1,
                'sort' => 0,
            ],
            [
                'id' => 97,
                'provider_id' => 1,
                'code' => 'SCEUB',
                'title' => '四川EUB',
                'en' => 'EUB-SICHUAN',
                'status' => 1,
                'sort' => 0,
            ],
            [
                'id' => 98,
                'provider_id' => 1,
                'code' => 'YSLDEZX',
                'title' => 'YSL专用',
                'en' => 'DEZXRYSL',
                'status' => 1,
                'sort' => 0,
            ],
            [
                'id' => 99,
                'provider_id' => 1,
                'code' => 'NLCP',
                'title' => '重派(荷兰DHL)',
                'en' => 'Reship Netherlands DHL',
                'status' => 1,
                'sort' => 0,
            ],
            [
                'id' => 100,
                'provider_id' => 1,
                'code' => 'ATCP',
                'title' => '重派奥地利',
                'en' => 'Austria Reship service',
                'status' => 1,
                'sort' => 0,
            ],
            [
                'id' => 101,
                'provider_id' => 1,
                'code' => 'FBA-TEST',
                'title' => '美国FBA测试渠道(请勿下单)',
                'en' => 'FBA-TEST',
                'status' => 1,
                'sort' => 0,
            ],
            [
                'id' => 102,
                'provider_id' => 1,
                'code' => 'STRCN',
                'title' => '华西速卖通线上挂号',
                'en' => 'SMT--XSRCD',
                'status' => 1,
                'sort' => 0,
            ],
            [
                'id' => 103,
                'provider_id' => 1,
                'code' => 'FZ-UPS',
                'title' => '福州UPS',
                'en' => 'FZ-UPS',
                'status' => 1,
                'sort' => 0,
            ],
            [
                'id' => 104,
                'provider_id' => 1,
                'code' => 'SHFBALAX',
                'title' => '中美UPS空派专线(上海)',
                'en' => 'SHFBALAX',
                'status' => 1,
                'sort' => 0,
            ],
            [
                'id' => 105,
                'provider_id' => 1,
                'code' => 'TW-UPS',
                'title' => '台湾UPS',
                'en' => 'TW-UPS',
                'status' => 1,
                'sort' => 0,
            ],
            [
                'id' => 106,
                'provider_id' => 1,
                'code' => 'CNPOSTP-BJ',
                'title' => '北京中邮小包平邮',
                'en' => 'BJ-china post',
                'status' => 1,
                'sort' => 0,
            ],
            [
                'id' => 107,
                'provider_id' => 1,
                'code' => 'SECP',
                'title' => '重派-瑞典专线挂号',
                'en' => 'Reship-Sweden',
                'status' => 1,
                'sort' => 0,
            ],
            [
                'id' => 108,
                'provider_id' => 1,
                'code' => 'XQDCS',
                'title' => '泰国测试专用',
                'en' => 'XQDCS',
                'status' => 1,
                'sort' => 0,
            ],
            [
                'id' => 109,
                'provider_id' => 1,
                'code' => 'FRZXRT',
                'title' => '法国专线挂号(退货)',
                'en' => 'YunExpress France Return Line',
                'status' => 1,
                'sort' => 0,
            ],
            [
                'id' => 110,
                'provider_id' => 1,
                'code' => 'WS-CD-G',
                'title' => 'wish邮挂号(CD)',
                'en' => 'Wishpost Registered Air Mial-CD',
                'status' => 1,
                'sort' => 0,
            ],
            [
                'id' => 111,
                'provider_id' => 1,
                'code' => 'WS-CD-P',
                'title' => 'wish邮平邮(CD)',
                'en' => 'Wishpost Registered Air Mial-CD-P',
                'status' => 1,
                'sort' => 0,
            ],
            [
                'id' => 112,
                'provider_id' => 1,
                'code' => 'PK0036',
                'title' => '四川SF特惠',
                'en' => 'Sichuan SF TH',
                'status' => 1,
                'sort' => 0,
            ],
            [
                'id' => 113,
                'provider_id' => 1,
                'code' => 'PL-CP',
                'title' => '波兰重派',
                'en' => 'Reship Poland',
                'status' => 1,
                'sort' => 0,
            ],
            [
                'id' => 114,
                'provider_id' => 1,
                'code' => 'PL-POST-CP',
                'title' => '波兰邮政重派',
                'en' => 'Reship PL-POST',
                'status' => 1,
                'sort' => 0,
            ],
            [
                'id' => 115,
                'provider_id' => 1,
                'code' => 'GE',
                'title' => '全球速运',
                'en' => 'global express',
                'status' => 1,
                'sort' => 0,
            ],
            [
                'id' => 116,
                'provider_id' => 1,
                'code' => 'SMT-XSR-B',
                'title' => '线上挂号(DG)-带电',
                'en' => 'Post on line-RB',
                'status' => 1,
                'sort' => 0,
            ],
            [
                'id' => 117,
                'provider_id' => 1,
                'code' => 'SMT-XSA-B',
                'title' => '线上平邮(DG)-带电',
                'en' => 'Post on line-AB',
                'status' => 1,
                'sort' => 0,
            ],
            [
                'id' => 118,
                'provider_id' => 1,
                'code' => 'CZ-CP',
                'title' => '捷克重派',
                'en' => 'Reship Czech Republic',
                'status' => 1,
                'sort' => 0,
            ],
            [
                'id' => 119,
                'provider_id' => 1,
                'code' => 'UPSQY',
                'title' => '四川UPS特惠',
                'en' => 'UPS Worlwide Expedited',
                'status' => 1,
                'sort' => 0,
            ],
            [
                'id' => 120,
                'provider_id' => 1,
                'code' => 'INPOST-CP',
                'title' => '波兰INPOST重派',
                'en' => 'Reship PL INPOST',
                'status' => 1,
                'sort' => 0,
            ],
            [
                'id' => 121,
                'provider_id' => 1,
                'code' => 'FBAUS-DDLY',
                'title' => 'FBA美国(普货)-FZ',
                'en' => 'FBAUS-FZ',
                'status' => 1,
                'sort' => 0,
            ],
            [
                'id' => 122,
                'provider_id' => 1,
                'code' => 'DEUB',
                'title' => '蓉易邮',
                'en' => 'RY-EUB',
                'status' => 1,
                'sort' => 0,
            ],
            [
                'id' => 123,
                'provider_id' => 1,
                'code' => 'XMEUB',
                'title' => '东南EUB',
                'en' => 'XMEUB',
                'status' => 1,
                'sort' => 0,
            ],
            [
                'id' => 124,
                'provider_id' => 1,
                'code' => 'STR-FEDEX',
                'title' => '四川-Fedex',
                'en' => 'Fedex',
                'status' => 1,
                'sort' => 0,
            ],
            [
                'id' => 125,
                'provider_id' => 1,
                'code' => 'ZYPY-CD',
                'title' => '成都平邮特惠',
                'en' => 'Chengdu Pingyou Preference',
                'status' => 1,
                'sort' => 0,
            ],
            [
                'id' => 126,
                'provider_id' => 1,
                'code' => 'ZYPY-HX',
                'title' => '华西小包平邮',
                'en' => 'nregistered Air Mail-Huaxi',
                'status' => 1,
                'sort' => 0,
            ],
            [
                'id' => 127,
                'provider_id' => 1,
                'code' => 'ZYGH-HX',
                'title' => '华西小包挂号',
                'en' => 'Registered Air Mail-HuaXi',
                'status' => 1,
                'sort' => 0,
            ],
            [
                'id' => 128,
                'provider_id' => 1,
                'code' => 'CP-EE',
                'title' => '爱沙尼亚重派',
                'en' => 'Estonia redelivery',
                'status' => 1,
                'sort' => 0,
            ],
            [
                'id' => 129,
                'provider_id' => 1,
                'code' => 'PK0047',
                'title' => '1212',
                'en' => '21212',
                'status' => 1,
                'sort' => 0,
            ],
        ]);
    }
}
