<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountriesSeeder extends Seeder
{
    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        DB::table('countries')->truncate();

        DB::table('countries')->insert([
            [
                'id' => 10,
                'code' => 'AQ',
                'en' => 'Antarctica',
                'name' => '',
            ],
            [
                'id' => 55,
                'code' => 'AF',
                'en' => 'Afghanistan',
                'name' => '',
            ],
            [
                'id' => 56,
                'code' => 'AO',
                'en' => 'Angola',
                'name' => '',
            ],
            [
                'id' => 57,
                'code' => 'AL',
                'en' => 'Albania',
                'name' => '',
            ],
            [
                'id' => 58,
                'code' => 'AE',
                'en' => 'United Arab Emirates',
                'name' => '',
            ],
            [
                'id' => 59,
                'code' => 'AR',
                'en' => 'Argentina',
                'name' => '',
            ],
            [
                'id' => 60,
                'code' => 'AM',
                'en' => 'Armenia',
                'name' => '',
            ],
            [
                'id' => 61,
                'code' => 'AU',
                'en' => 'Australia',
                'name' => '',
            ],
            [
                'id' => 62,
                'code' => 'AT',
                'en' => 'Austria',
                'name' => '',
            ],
            [
                'id' => 63,
                'code' => 'AZ',
                'en' => 'Azerbaijan',
                'name' => '',
            ],
            [
                'id' => 64,
                'code' => 'BI',
                'en' => 'Burundi',
                'name' => '',
            ],
            [
                'id' => 65,
                'code' => 'BE',
                'en' => 'Belgium',
                'name' => '',
            ],
            [
                'id' => 66,
                'code' => 'BJ',
                'en' => 'Benin',
                'name' => '',
            ],
            [
                'id' => 67,
                'code' => 'BF',
                'en' => 'Burkina Faso',
                'name' => '',
            ],
            [
                'id' => 68,
                'code' => 'BD',
                'en' => 'Bangladesh',
                'name' => '',
            ],
            [
                'id' => 69,
                'code' => 'BG',
                'en' => 'Bulgaria',
                'name' => '',
            ],
            [
                'id' => 70,
                'code' => 'BA',
                'en' => 'Bosnia and Herzegovina',
                'name' => '',
            ],
            [
                'id' => 71,
                'code' => 'BY',
                'en' => 'Belarus',
                'name' => '',
            ],
            [
                'id' => 72,
                'code' => 'BZ',
                'en' => 'Belize',
                'name' => '',
            ],
            [
                'id' => 73,
                'code' => 'BO',
                'en' => 'Bolivia',
                'name' => '',
            ],
            [
                'id' => 74,
                'code' => 'BR',
                'en' => 'Brazil',
                'name' => '',
            ],
            [
                'id' => 75,
                'code' => 'BN',
                'en' => 'Brunei',
                'name' => '',
            ],
            [
                'id' => 76,
                'code' => 'BT',
                'en' => 'Bhutan',
                'name' => '',
            ],
            [
                'id' => 77,
                'code' => 'BW',
                'en' => 'Botswana',
                'name' => '',
            ],
            [
                'id' => 78,
                'code' => 'CF',
                'en' => 'Central African Republic',
                'name' => '',
            ],
            [
                'id' => 79,
                'code' => 'CA',
                'en' => 'Canada',
                'name' => '',
            ],
            [
                'id' => 80,
                'code' => 'CH',
                'en' => 'Switzerland',
                'name' => '',
            ],
            [
                'id' => 81,
                'code' => 'CL',
                'en' => 'Chile',
                'name' => '',
            ],
            [
                'id' => 82,
                'code' => 'CN',
                'en' => 'China',
                'name' => '',
            ],
            [
                'id' => 83,
                'code' => 'IC',
                'en' => 'Ivory Coast',
                'name' => '',
            ],
            [
                'id' => 84,
                'code' => 'CM',
                'en' => 'Cameroon',
                'name' => '',
            ],
            [
                'id' => 85,
                'code' => 'CG',
                'en' => 'Congo, Republic of',
                'name' => '',
            ],
            [
                'id' => 86,
                'code' => 'CO',
                'en' => 'Colombia',
                'name' => '',
            ],
            [
                'id' => 87,
                'code' => 'CR',
                'en' => 'Costa Rica',
                'name' => '',
            ],
            [
                'id' => 89,
                'code' => 'CY',
                'en' => 'Cyprus',
                'name' => '',
            ],
            [
                'id' => 90,
                'code' => 'CZ',
                'en' => 'Czech Republic',
                'name' => '',
            ],
            [
                'id' => 91,
                'code' => 'DE',
                'en' => 'Germany',
                'name' => '',
            ],
            [
                'id' => 92,
                'code' => 'DJ',
                'en' => 'Djibouti',
                'name' => '',
            ],
            [
                'id' => 93,
                'code' => 'DK',
                'en' => 'Denmark',
                'name' => '',
            ],
            [
                'id' => 94,
                'code' => 'DO',
                'en' => 'Dominican Republic',
                'name' => '',
            ],
            [
                'id' => 95,
                'code' => 'DZ',
                'en' => 'Algeria',
                'name' => '',
            ],
            [
                'id' => 96,
                'code' => 'EC',
                'en' => 'Ecuador',
                'name' => '',
            ],
            [
                'id' => 97,
                'code' => 'EG',
                'en' => 'Egypt',
                'name' => '',
            ],
            [
                'id' => 98,
                'code' => 'ER',
                'en' => 'Eritrea',
                'name' => '',
            ],
            [
                'id' => 99,
                'code' => 'ES',
                'en' => 'Spain',
                'name' => '',
            ],
            [
                'id' => 100,
                'code' => 'EE',
                'en' => 'Estonia',
                'name' => '',
            ],
            [
                'id' => 101,
                'code' => 'ET',
                'en' => 'Ethiopia',
                'name' => '',
            ],
            [
                'id' => 102,
                'code' => 'FI',
                'en' => 'Finland',
                'name' => '',
            ],
            [
                'id' => 103,
                'code' => 'FR',
                'en' => 'France',
                'name' => '',
            ],
            [
                'id' => 104,
                'code' => 'GA',
                'en' => 'Gabon',
                'name' => '',
            ],
            [
                'id' => 105,
                'code' => 'GB',
                'en' => 'United Kingdom',
                'name' => '',
            ],
            [
                'id' => 106,
                'code' => 'GE',
                'en' => 'Georgia',
                'name' => '',
            ],
            [
                'id' => 107,
                'code' => 'GH',
                'en' => 'Ghana',
                'name' => '',
            ],
            [
                'id' => 108,
                'code' => 'GN',
                'en' => 'Guinea',
                'name' => '',
            ],
            [
                'id' => 109,
                'code' => 'GM',
                'en' => 'Gambia',
                'name' => '',
            ],
            [
                'id' => 110,
                'code' => 'GW',
                'en' => 'Guinea-Bissau',
                'name' => '',
            ],
            [
                'id' => 111,
                'code' => 'GQ',
                'en' => 'Equatorial Guinea',
                'name' => '',
            ],
            [
                'id' => 112,
                'code' => 'GR',
                'en' => 'Greece',
                'name' => '',
            ],
            [
                'id' => 113,
                'code' => 'GL',
                'en' => 'Greenland',
                'name' => '',
            ],
            [
                'id' => 114,
                'code' => 'GT',
                'en' => 'Guatemala',
                'name' => '',
            ],
            [
                'id' => 115,
                'code' => 'GF',
                'en' => 'French Guiana',
                'name' => '',
            ],
            [
                'id' => 116,
                'code' => 'GY',
                'en' => 'Guyana',
                'name' => '',
            ],
            [
                'id' => 117,
                'code' => 'HN',
                'en' => 'Honduras',
                'name' => '',
            ],
            [
                'id' => 118,
                'code' => 'HR',
                'en' => 'Croatia',
                'name' => '',
            ],
            [
                'id' => 119,
                'code' => 'HT',
                'en' => 'Haiti',
                'name' => '',
            ],
            [
                'id' => 120,
                'code' => 'HU',
                'en' => 'Hungary',
                'name' => '',
            ],
            [
                'id' => 121,
                'code' => 'ID',
                'en' => 'Indonesia',
                'name' => '',
            ],
            [
                'id' => 122,
                'code' => 'IN',
                'en' => 'India',
                'name' => '',
            ],
            [
                'id' => 123,
                'code' => 'IE',
                'en' => 'Ireland',
                'name' => '',
            ],
            [
                'id' => 125,
                'code' => 'IQ',
                'en' => 'Iraq',
                'name' => '',
            ],
            [
                'id' => 126,
                'code' => 'IS',
                'en' => 'Iceland',
                'name' => '',
            ],
            [
                'id' => 127,
                'code' => 'IL',
                'en' => 'Israel',
                'name' => '',
            ],
            [
                'id' => 128,
                'code' => 'IT',
                'en' => 'Italy',
                'name' => '',
            ],
            [
                'id' => 129,
                'code' => 'JM',
                'en' => 'Jamaica',
                'name' => '',
            ],
            [
                'id' => 130,
                'code' => 'JO',
                'en' => 'Jordan',
                'name' => '',
            ],
            [
                'id' => 131,
                'code' => 'JP',
                'en' => 'Japan',
                'name' => '',
            ],
            [
                'id' => 132,
                'code' => 'KZ',
                'en' => 'Kazakhstan',
                'name' => '',
            ],
            [
                'id' => 133,
                'code' => 'KE',
                'en' => 'Kenya',
                'name' => '',
            ],
            [
                'id' => 134,
                'code' => 'KG',
                'en' => 'Kyrgyzstan',
                'name' => '',
            ],
            [
                'id' => 135,
                'code' => 'KH',
                'en' => 'Cambodia',
                'name' => '',
            ],
            [
                'id' => 136,
                'code' => 'KR',
                'en' => 'South Korea',
                'name' => '',
            ],
            [
                'id' => 137,
                'code' => 'KW',
                'en' => 'Kuwait',
                'name' => '',
            ],
            [
                'id' => 138,
                'code' => 'LA',
                'en' => 'Laos',
                'name' => '',
            ],
            [
                'id' => 139,
                'code' => 'LB',
                'en' => 'Lebanon',
                'name' => '',
            ],
            [
                'id' => 140,
                'code' => 'LR',
                'en' => 'Liberia',
                'name' => '',
            ],
            [
                'id' => 141,
                'code' => 'LY',
                'en' => 'Libya',
                'name' => '',
            ],
            [
                'id' => 142,
                'code' => 'LK',
                'en' => 'Sri Lanka',
                'name' => '',
            ],
            [
                'id' => 143,
                'code' => 'LS',
                'en' => 'Lesotho',
                'name' => '',
            ],
            [
                'id' => 144,
                'code' => 'LT',
                'en' => 'Lithuania',
                'name' => '',
            ],
            [
                'id' => 145,
                'code' => 'LU',
                'en' => 'Luxembourg',
                'name' => '',
            ],
            [
                'id' => 146,
                'code' => 'LV',
                'en' => 'Latvia',
                'name' => '',
            ],
            [
                'id' => 147,
                'code' => 'MA',
                'en' => 'Morocco',
                'name' => '',
            ],
            [
                'id' => 148,
                'code' => 'MD',
                'en' => 'Moldova',
                'name' => '',
            ],
            [
                'id' => 149,
                'code' => 'MG',
                'en' => 'Madagascar',
                'name' => '',
            ],
            [
                'id' => 150,
                'code' => 'MX',
                'en' => 'Mexico',
                'name' => '',
            ],
            [
                'id' => 151,
                'code' => 'MK',
                'en' => 'Macedonia',
                'name' => '',
            ],
            [
                'id' => 152,
                'code' => 'ML',
                'en' => 'Mali',
                'name' => '',
            ],
            [
                'id' => 153,
                'code' => 'MM',
            'en' => 'Myanmar (Burma)',
                'name' => '',
            ],
            [
                'id' => 154,
                'code' => 'MN',
                'en' => 'Mongolia',
                'name' => '',
            ],
            [
                'id' => 155,
                'code' => 'ME',
                'en' => 'Montenegro',
                'name' => '',
            ],
            [
                'id' => 156,
                'code' => 'MZ',
                'en' => 'Mozambique',
                'name' => '',
            ],
            [
                'id' => 157,
                'code' => 'MR',
                'en' => 'Mauritania',
                'name' => '',
            ],
            [
                'id' => 158,
                'code' => 'MW',
                'en' => 'Malawi',
                'name' => '',
            ],
            [
                'id' => 159,
                'code' => 'MY',
                'en' => 'Malaysia',
                'name' => '',
            ],
            [
                'id' => 160,
                'code' => 'NA',
                'en' => 'Namibia',
                'name' => '',
            ],
            [
                'id' => 161,
                'code' => 'NE',
                'en' => 'Niger',
                'name' => '',
            ],
            [
                'id' => 162,
                'code' => 'NG',
                'en' => 'Nigeria',
                'name' => '',
            ],
            [
                'id' => 163,
                'code' => 'NI',
                'en' => 'Nicaragua',
                'name' => '',
            ],
            [
                'id' => 164,
                'code' => 'NL',
                'en' => 'The Netherlands',
                'name' => '',
            ],
            [
                'id' => 165,
                'code' => 'NO',
                'en' => 'Norway',
                'name' => '',
            ],
            [
                'id' => 166,
                'code' => 'NP',
                'en' => 'Nepal',
                'name' => '',
            ],
            [
                'id' => 167,
                'code' => 'NZ',
                'en' => 'New Zealand',
                'name' => '',
            ],
            [
                'id' => 168,
                'code' => 'OM',
                'en' => 'Oman',
                'name' => '',
            ],
            [
                'id' => 169,
                'code' => 'PK',
                'en' => 'Pakistan',
                'name' => '',
            ],
            [
                'id' => 170,
                'code' => 'PA',
                'en' => 'Panama',
                'name' => '',
            ],
            [
                'id' => 171,
                'code' => 'PE',
                'en' => 'Peru',
                'name' => '',
            ],
            [
                'id' => 172,
                'code' => 'PH',
                'en' => 'Philippines',
                'name' => '',
            ],
            [
                'id' => 173,
                'code' => 'PG',
                'en' => 'Papua New Guinea',
                'name' => '',
            ],
            [
                'id' => 174,
                'code' => 'PL',
                'en' => 'Poland',
                'name' => '',
            ],
            [
                'id' => 175,
                'code' => 'PR',
                'en' => 'Puerto Rico',
                'name' => '',
            ],
            [
                'id' => 177,
                'code' => 'PT',
                'en' => 'Portugal',
                'name' => '',
            ],
            [
                'id' => 178,
                'code' => 'PY',
                'en' => 'Paraguay',
                'name' => '',
            ],
            [
                'id' => 179,
                'code' => 'QA',
                'en' => 'Qatar',
                'name' => '',
            ],
            [
                'id' => 180,
                'code' => 'RO',
                'en' => 'Romania',
                'name' => '',
            ],
            [
                'id' => 181,
                'code' => 'RU',
                'en' => 'Russia',
                'name' => '',
            ],
            [
                'id' => 182,
                'code' => 'RW',
                'en' => 'Rwanda',
                'name' => '',
            ],
            [
                'id' => 183,
                'code' => 'SA',
                'en' => 'Saudi Arabia',
                'name' => '',
            ],
            [
                'id' => 184,
                'code' => 'SD',
                'en' => 'Sudan',
                'name' => '',
            ],
            [
                'id' => 185,
                'code' => 'SN',
                'en' => 'Senegal',
                'name' => '',
            ],
            [
                'id' => 186,
                'code' => 'SL',
                'en' => 'Sierra Leone',
                'name' => '',
            ],
            [
                'id' => 187,
                'code' => 'SV',
                'en' => 'El Salvador',
                'name' => '',
            ],
            [
                'id' => 188,
                'code' => 'SO',
                'en' => 'Somalia',
                'name' => '',
            ],
            [
                'id' => 189,
                'code' => 'RS',
                'en' => 'Serbia',
                'name' => '',
            ],
            [
                'id' => 190,
                'code' => 'SR',
                'en' => 'Suriname',
                'name' => '',
            ],
            [
                'id' => 191,
                'code' => 'SK',
                'en' => 'Slovakia',
                'name' => '',
            ],
            [
                'id' => 192,
                'code' => 'SI',
                'en' => 'Slovenia',
                'name' => '',
            ],
            [
                'id' => 193,
                'code' => 'SE',
                'en' => 'Sweden',
                'name' => '',
            ],
            [
                'id' => 194,
                'code' => 'SZ',
                'en' => 'Swaziland',
                'name' => '',
            ],
            [
                'id' => 196,
                'code' => 'TD',
                'en' => 'Chad',
                'name' => '',
            ],
            [
                'id' => 197,
                'code' => 'TG',
                'en' => 'Togo',
                'name' => '',
            ],
            [
                'id' => 198,
                'code' => 'TH',
                'en' => 'Thailand',
                'name' => '',
            ],
            [
                'id' => 199,
                'code' => 'TJ',
                'en' => 'Tajikistan',
                'name' => '',
            ],
            [
                'id' => 200,
                'code' => 'TM',
                'en' => 'Turkmenistan',
                'name' => '',
            ],
            [
                'id' => 201,
                'code' => 'TT',
                'en' => 'Trinidad',
                'name' => '',
            ],
            [
                'id' => 202,
                'code' => 'TN',
                'en' => 'Tunisia',
                'name' => '',
            ],
            [
                'id' => 203,
                'code' => 'TR',
                'en' => 'Turkey',
                'name' => '',
            ],
            [
                'id' => 204,
                'code' => 'TW',
                'en' => 'Taiwan',
                'name' => '',
            ],
            [
                'id' => 205,
                'code' => 'TZ',
                'en' => 'Tanzania',
                'name' => '',
            ],
            [
                'id' => 206,
                'code' => 'UG',
                'en' => 'Uganda',
                'name' => '',
            ],
            [
                'id' => 207,
                'code' => 'UA',
                'en' => 'Ukraine',
                'name' => '',
            ],
            [
                'id' => 208,
                'code' => 'UY',
                'en' => 'Uruguay',
                'name' => '',
            ],
            [
                'id' => 209,
                'code' => 'US',
                'en' => 'United States',
                'name' => '',
            ],
            [
                'id' => 210,
                'code' => 'UZ',
                'en' => 'Uzbekistan',
                'name' => '',
            ],
            [
                'id' => 211,
                'code' => 'VE',
                'en' => 'Venezuela',
                'name' => '',
            ],
            [
                'id' => 212,
                'code' => 'VN',
                'en' => 'Vietnam',
                'name' => '',
            ],
            [
                'id' => 213,
                'code' => 'EH',
                'en' => 'Western Sahara',
                'name' => '',
            ],
            [
                'id' => 214,
                'code' => 'YE',
                'en' => 'Yemen',
                'name' => '',
            ],
            [
                'id' => 215,
                'code' => 'ZA',
                'en' => 'South Africa',
                'name' => '',
            ],
            [
                'id' => 216,
                'code' => 'CD',
            'en' => 'Zaire (Democratic Republic of Congo)',
                'name' => '',
            ],
            [
                'id' => 217,
                'code' => 'ZM',
                'en' => 'Zambia',
                'name' => '',
            ],
            [
                'id' => 218,
                'code' => 'ZW',
                'en' => 'Zimbabwe',
                'name' => '',
            ],
            [
                'id' => 219,
                'code' => 'HK',
                'en' => 'Hong Kong',
                'name' => '',
            ],
            [
                'id' => 220,
                'code' => 'SG',
                'en' => 'Singapore',
                'name' => '',
            ],
            [
                'id' => 221,
                'code' => 'VU',
                'en' => 'Vanuatu',
                'name' => '',
            ],
            [
                'id' => 222,
                'code' => 'CV',
                'en' => 'Cape Verde',
                'name' => '',
            ],
            [
                'id' => 224,
                'code' => 'WF',
                'en' => 'Wallis and Futuna',
                'name' => '',
            ],
            [
                'id' => 225,
                'code' => 'BM',
                'en' => 'Bermuda',
                'name' => '',
            ],
            [
                'id' => 226,
                'code' => 'GI',
                'en' => 'Gibraltar',
                'name' => '',
            ],
            [
                'id' => 227,
                'code' => 'MT',
                'en' => 'Malta',
                'name' => '',
            ],
            [
                'id' => 228,
                'code' => 'AD',
                'en' => 'Andorra',
                'name' => '',
            ],
            [
                'id' => 229,
                'code' => 'BS',
                'en' => 'Bahamas',
                'name' => '',
            ],
            [
                'id' => 231,
                'code' => 'VG',
                'en' => 'British Virgin Islands',
                'name' => '',
            ],
            [
                'id' => 232,
                'code' => 'BH',
                'en' => 'Bahrain',
                'name' => '',
            ],
            [
                'id' => 233,
                'code' => 'NC',
                'en' => 'New Caledonia',
                'name' => '',
            ],
            [
                'id' => 234,
                'code' => 'FJ',
                'en' => 'Fiji',
                'name' => '',
            ],
            [
                'id' => 237,
                'code' => 'BB',
                'en' => 'Barbados',
                'name' => '',
            ],
            [
                'id' => 238,
                'code' => 'MV',
                'en' => 'Maldives',
                'name' => '',
            ],
            [
                'id' => 239,
                'code' => 'MU',
                'en' => 'Mauritius',
                'name' => '',
            ],
            [
                'id' => 241,
                'code' => 'FO',
                'en' => 'Faroe Islands',
                'name' => '',
            ],
            [
                'id' => 242,
                'code' => 'SB',
                'en' => 'Solomon Islands',
                'name' => '',
            ],
            [
                'id' => 243,
                'code' => 'AN',
                'en' => 'Netherlands Antilles',
                'name' => '',
            ],
            [
                'id' => 244,
                'code' => 'LC',
                'en' => 'Saint Lucia',
                'name' => '',
            ],
            [
                'id' => 245,
                'code' => 'GD',
                'en' => 'Grenada',
                'name' => '',
            ],
            [
                'id' => 247,
                'code' => 'KY',
                'en' => 'Cayman Islands',
                'name' => '',
            ],
            [
                'id' => 248,
                'code' => 'VI',
                'en' => 'U.S. Virgin Islands',
                'name' => '',
            ],
            [
                'id' => 249,
                'code' => 'VC',
                'en' => 'Saint Vincent and the Grenadines',
                'name' => '',
            ],
            [
                'id' => 250,
                'code' => 'AS',
                'en' => 'American Samoa',
                'name' => '',
            ],
            [
                'id' => 251,
                'code' => 'AI',
                'en' => 'Anguilla',
                'name' => '',
            ],
            [
                'id' => 252,
                'code' => 'AG',
                'en' => 'Antigua and Barbuda',
                'name' => '',
            ],
            [
                'id' => 253,
                'code' => 'AW',
                'en' => 'Aruba',
                'name' => '',
            ],
            [
                'id' => 254,
                'code' => 'BV',
                'en' => 'Bouvet Island',
                'name' => '',
            ],
            [
                'id' => 255,
                'code' => 'IO',
                'en' => 'British Indian Ocean Territory',
                'name' => '',
            ],
            [
                'id' => 257,
                'code' => 'CX',
                'en' => 'Christmas Island',
                'name' => '',
            ],
            [
                'id' => 258,
                'code' => 'CC',
            'en' => 'Cocos (Keeling) Islands',
                'name' => '',
            ],
            [
                'id' => 259,
                'code' => 'KM',
                'en' => 'Comoros',
                'name' => '',
            ],
            [
                'id' => 260,
                'code' => 'CK',
                'en' => 'Cook Islands',
                'name' => '',
            ],
            [
                'id' => 261,
                'code' => 'DM',
                'en' => 'Dominica',
                'name' => '',
            ],
            [
                'id' => 262,
                'code' => 'FK',
            'en' => 'Falkland Islands (Malvinas)',
                'name' => '',
            ],
            [
                'id' => 263,
                'code' => 'PF',
                'en' => 'French Polynesia',
                'name' => '',
            ],
            [
                'id' => 264,
                'code' => 'TF',
                'en' => 'French Southern Territories',
                'name' => '',
            ],
            [
                'id' => 265,
                'code' => 'GP',
                'en' => 'Guadeloupe',
                'name' => '',
            ],
            [
                'id' => 266,
                'code' => 'GU',
                'en' => 'Guam',
                'name' => '',
            ],
            [
                'id' => 267,
                'code' => 'HM',
                'en' => 'Heard Island and McDonald Islands',
                'name' => '',
            ],
            [
                'id' => 268,
                'code' => 'VA',
            'en' => 'Holy See (Vatican City State)',
                'name' => '',
            ],
            [
                'id' => 269,
                'code' => 'IM',
                'en' => 'Isle of Man',
                'name' => '',
            ],
            [
                'id' => 270,
                'code' => 'KI',
                'en' => 'Kiribati',
                'name' => '',
            ],
            [
                'id' => 271,
                'code' => 'KV',
                'en' => 'Kosovo',
                'name' => '',
            ],
            [
                'id' => 272,
                'code' => 'LI',
                'en' => 'Liechtenstein',
                'name' => '',
            ],
            [
                'id' => 273,
                'code' => 'MO',
                'en' => 'Macao',
                'name' => '',
            ],
            [
                'id' => 274,
                'code' => 'MH',
                'en' => 'Marshall Islands',
                'name' => '',
            ],
            [
                'id' => 275,
                'code' => 'MQ',
                'en' => 'Martinique',
                'name' => '',
            ],
            [
                'id' => 276,
                'code' => 'YT',
                'en' => 'Mayotte',
                'name' => '',
            ],
            [
                'id' => 277,
                'code' => 'FM',
                'en' => 'Micronesia, Federated States of',
                'name' => '',
            ],
            [
                'id' => 278,
                'code' => 'MC',
                'en' => 'Monaco',
                'name' => '',
            ],
            [
                'id' => 279,
                'code' => 'MS',
                'en' => 'Montserrat',
                'name' => '',
            ],
            [
                'id' => 280,
                'code' => 'NR',
                'en' => 'Nauru',
                'name' => '',
            ],
            [
                'id' => 281,
                'code' => 'NU',
                'en' => 'Niue',
                'name' => '',
            ],
            [
                'id' => 282,
                'code' => 'NF',
                'en' => 'Norfolk Island',
                'name' => '',
            ],
            [
                'id' => 283,
                'code' => 'MP',
                'en' => 'Northern Mariana Islands',
                'name' => '',
            ],
            [
                'id' => 284,
                'code' => 'PW',
                'en' => 'Palau',
                'name' => '',
            ],
            [
                'id' => 285,
                'code' => 'PS',
                'en' => 'Palestine, State of',
                'name' => '',
            ],
            [
                'id' => 286,
                'code' => 'SH',
                'en' => 'Saint Helena',
                'name' => '',
            ],
            [
                'id' => 287,
                'code' => 'KN',
                'en' => 'Saint Kitts and Nevis',
                'name' => '',
            ],
            [
                'id' => 288,
                'code' => 'MF',
            'en' => 'Saint Martin (French part)',
                'name' => '',
            ],
            [
                'id' => 289,
                'code' => 'PM',
                'en' => 'Saint Pierre and Miquelon',
                'name' => '',
            ],
            [
                'id' => 290,
                'code' => 'WS',
                'en' => 'Samoa',
                'name' => '',
            ],
            [
                'id' => 291,
                'code' => 'SM',
                'en' => 'San Marino',
                'name' => '',
            ],
            [
                'id' => 292,
                'code' => 'ST',
                'en' => 'Sao Tome and Principe',
                'name' => '',
            ],
            [
                'id' => 293,
                'code' => 'SC',
                'en' => 'Seychelles',
                'name' => '',
            ],
            [
                'id' => 294,
                'code' => 'GS',
                'en' => 'South Georgia and the South Sandwich Islands',
                'name' => '',
            ],
            [
                'id' => 295,
                'code' => 'SJ',
                'en' => 'Svalbard and Jan Mayen',
                'name' => '',
            ],
            [
                'id' => 296,
                'code' => 'TL',
                'en' => 'Timor-Leste',
                'name' => '',
            ],
            [
                'id' => 297,
                'code' => 'TK',
                'en' => 'Tokelau',
                'name' => '',
            ],
            [
                'id' => 298,
                'code' => 'TO',
                'en' => 'Tonga',
                'name' => '',
            ],
            [
                'id' => 299,
                'code' => 'TC',
                'en' => 'Turks and Caicos Islands',
                'name' => '',
            ],
            [
                'id' => 300,
                'code' => 'TV',
                'en' => 'Tuvalu',
                'name' => '',
            ],
            [
                'id' => 302,
                'code' => 'UM',
                'en' => 'United States Minor Outlying Islands',
                'name' => '',
            ],
            [
                'id' => 304,
                'code' => 'RE',
                'en' => 'Reunion',
                'name' => '',
            ],
            [
                'id' => 305,
                'code' => 'GG',
                'en' => 'Guernsey',
                'name' => '',
            ],
            [
                'id' => 306,
                'code' => 'AX',
                'en' => 'Åland Islands',
                'name' => '',
            ],
            [
                'id' => 307,
                'code' => 'JE',
                'en' => 'Jersey',
                'name' => '',
            ],
            [
                'id' => 308,
                'code' => 'BL',
                'en' => 'Saint Barthélemy',
                'name' => '',
            ],
            [
                'id' => 337,
                'code' => 'SX',
            'en' => 'Sint Maarten (Dutch part)',
                'name' => '',
            ],
            [
                'id' => 338,
                'code' => 'CW',
                'en' => 'Curaçao',
                'name' => '',
            ],
            [
                'id' => 339,
                'code' => 'SS',
                'en' => 'South Sudan',
                'name' => '',
            ],
            [
                'id' => 535,
                'code' => 'BQ',
                'en' => 'Bonaire, Sint Eustatius and Saba',
                'name' => '',
            ],
            [
                'id' => 891,
                'code' => 'CS',
                'en' => 'Serbia and Montenegro',
                'name' => '',
            ],
        ]);
    }
}
